/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jorgealvarez_lab5;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ofici
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal2() {
        initComponents();
        Equipos.add(new Equipo("Barcelona", "España", new Tecnico(Float.parseFloat("12.5"), 12, "Defensivo"), 0));
        Equipos.add(new Equipo("Real Madrid", "España", new Tecnico(Float.parseFloat("12.5"), 1, "Defensivo"), 0));
        Jugadores.add(new Jugador(1, "I", "Delantero", WIDTH, TOP_ALIGNMENT, TOP_ALIGNMENT, "Neymar", WIDTH, "París", TOP_ALIGNMENT));
        Jugadores.add(new Jugador(1, "I", "Delantero", WIDTH, TOP_ALIGNMENT, TOP_ALIGNMENT, "Alejandro", WIDTH, "Francia", TOP_ALIGNMENT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarEquipo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        NombreEquipoTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PaisEquipoTf = new javax.swing.JTextField();
        AgregarEquipoJdBt = new javax.swing.JButton();
        AgregarTecnico = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        NombreTecnicoTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SalarioTecnicoTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EdadTecnicoTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PaisTecnicoTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TiempoDeTrabajoTecnicoTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CalidadTecnicoTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TipoDeJuegoTecnicoTf = new javax.swing.JTextField();
        AgregarTecnicoJdBt = new javax.swing.JButton();
        AgregarJugador = new javax.swing.JDialog();
        NombreJugadorTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SalarioJugadorTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        EdadJugadorTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PaisJugadorTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        IzquierdoRb = new javax.swing.JRadioButton();
        DerechoRb = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        CalidadJugadorTf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        VelocidadJugadorTf = new javax.swing.JTextField();
        PrecioJugadorTf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        PosicionJugadorCb = new javax.swing.JComboBox<>();
        PiernaPreferidaBg = new javax.swing.ButtonGroup();
        ListarBg = new javax.swing.ButtonGroup();
        MenuClickDerecho = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Principal = new javax.swing.JTabbedPane();
        CreacionDeElementosPa = new javax.swing.JPanel();
        AgregarEquipoBt = new javax.swing.JButton();
        AgregarTecnicoBt = new javax.swing.JButton();
        AgregarJugadorBt = new javax.swing.JButton();
        ListarElementosPa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListarTb = new javax.swing.JTable();
        ListarEquiposRb = new javax.swing.JRadioButton();
        ListarTecnicosRb = new javax.swing.JRadioButton();
        ListarJugadoresRb = new javax.swing.JRadioButton();
        AgregarJugadoresAEquipoPa = new javax.swing.JPanel();
        AgregarJugadorCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgregarJugadorLi = new javax.swing.JList<>();
        AgregarJugadorNombreLi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ActualizarListaAgregarEquipoBt = new javax.swing.JButton();
        MostrarPlantillasPa = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MostrarPlantillasArbol = new javax.swing.JTree();
        OrganizarPartidosPa = new javax.swing.JPanel();
        Equipo1Cb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JugarPartidoBt = new javax.swing.JButton();
        Equipo2Cb = new javax.swing.JComboBox<>();
        MostrarRankingPa = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        RankingTb = new javax.swing.JTable();

        jLabel1.setText("Nombre");

        jLabel2.setText("País");

        AgregarEquipoJdBt.setText("Agregar Equipo");
        AgregarEquipoJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarEquipoJdBtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AgregarEquipoLayout = new javax.swing.GroupLayout(AgregarEquipo.getContentPane());
        AgregarEquipo.getContentPane().setLayout(AgregarEquipoLayout);
        AgregarEquipoLayout.setHorizontalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarEquipoLayout.createSequentialGroup()
                        .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaisEquipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreEquipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AgregarEquipoJdBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AgregarEquipoLayout.setVerticalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreEquipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaisEquipoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(AgregarEquipoJdBt)
                .addContainerGap())
        );

        jLabel3.setText("Nombre");

        jLabel4.setText("País");

        jLabel5.setText("Salario");

        jLabel6.setText("Edad");

        jLabel7.setText("Tiempo de Trabajo (años)");

        jLabel8.setText("Calidad");

        jLabel9.setText("Tipo de Juego");

        AgregarTecnicoJdBt.setText("Agregar Técnico");
        AgregarTecnicoJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarTecnicoJdBtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AgregarTecnicoLayout = new javax.swing.GroupLayout(AgregarTecnico.getContentPane());
        AgregarTecnico.getContentPane().setLayout(AgregarTecnicoLayout);
        AgregarTecnicoLayout.setHorizontalGroup(
            AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarTecnicoLayout.createSequentialGroup()
                        .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarTecnicoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(119, 119, 119)
                                .addComponent(CalidadTecnicoTf))
                            .addGroup(AgregarTecnicoLayout.createSequentialGroup()
                                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31)
                                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TiempoDeTrabajoTecnicoTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(EdadTecnicoTf)
                                    .addComponent(SalarioTecnicoTf)
                                    .addComponent(NombreTecnicoTf)
                                    .addComponent(PaisTecnicoTf, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarTecnicoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(TipoDeJuegoTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(AgregarTecnicoJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AgregarTecnicoLayout.setVerticalGroup(
            AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EdadTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PaisTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SalarioTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TiempoDeTrabajoTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CalidadTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TipoDeJuegoTecnicoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(AgregarTecnicoJdBt)
                .addContainerGap())
        );

        jLabel10.setText("Posición");

        jLabel11.setText("País");

        jLabel12.setText("Salario");

        jLabel13.setText("Edad");

        jLabel15.setText("Nombre");

        jLabel16.setText("Pie preferido");

        PiernaPreferidaBg.add(IzquierdoRb);
        IzquierdoRb.setText("Izquierdo");

        PiernaPreferidaBg.add(DerechoRb);
        DerechoRb.setText("Derecho");

        jLabel17.setText("Calidad");

        jLabel18.setText("Velocidad");

        jLabel19.setText("Precio");

        jButton2.setText("Agregar Jugador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        PosicionJugadorCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Medio", "Delantero" }));

        javax.swing.GroupLayout AgregarJugadorLayout = new javax.swing.GroupLayout(AgregarJugador.getContentPane());
        AgregarJugador.getContentPane().setLayout(AgregarJugadorLayout);
        AgregarJugadorLayout.setHorizontalGroup(
            AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarJugadorLayout.createSequentialGroup()
                        .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarJugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PrecioJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarJugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(VelocidadJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarJugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CalidadJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(AgregarJugadorLayout.createSequentialGroup()
                                    .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EdadJugadorTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(SalarioJugadorTf)
                                        .addComponent(NombreJugadorTf)
                                        .addComponent(PaisJugadorTf, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AgregarJugadorLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(87, 87, 87)
                                    .addComponent(PosicionJugadorCb, 0, 91, Short.MAX_VALUE)))
                            .addGroup(AgregarJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(64, 64, 64)
                                .addComponent(IzquierdoRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DerechoRb)))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarJugadorLayout.setVerticalGroup(
            AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(NombreJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(EdadJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(PaisJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SalarioJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(IzquierdoRb)
                    .addComponent(DerechoRb))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PosicionJugadorCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CalidadJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(VelocidadJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(PrecioJugadorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrincipalStateChanged(evt);
            }
        });

        AgregarEquipoBt.setText("Agregar Equipo");
        AgregarEquipoBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarEquipoBtMouseClicked(evt);
            }
        });

        AgregarTecnicoBt.setText("Agregar Técnico");
        AgregarTecnicoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTecnicoBtActionPerformed(evt);
            }
        });

        AgregarJugadorBt.setText("Agregar Jugador");
        AgregarJugadorBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJugadorBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreacionDeElementosPaLayout = new javax.swing.GroupLayout(CreacionDeElementosPa);
        CreacionDeElementosPa.setLayout(CreacionDeElementosPaLayout);
        CreacionDeElementosPaLayout.setHorizontalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AgregarJugadorBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarEquipoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarTecnicoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(604, Short.MAX_VALUE))
        );
        CreacionDeElementosPaLayout.setVerticalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarEquipoBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarTecnicoBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarJugadorBt)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        Principal.addTab("Creación de Elementos", CreacionDeElementosPa);

        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "País", "Calidad", "Técnico del equipo", "Puntos"
            }
        ));
        ListarTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarTbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListarTb);

        ListarBg.add(ListarEquiposRb);
        ListarEquiposRb.setText("Listar Equipos");
        ListarEquiposRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarEquiposRbActionPerformed(evt);
            }
        });

        ListarBg.add(ListarTecnicosRb);
        ListarTecnicosRb.setText("Listar Técnicos");
        ListarTecnicosRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTecnicosRbActionPerformed(evt);
            }
        });

        ListarBg.add(ListarJugadoresRb);
        ListarJugadoresRb.setText("Listar Jugadores");
        ListarJugadoresRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarJugadoresRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListarElementosPaLayout = new javax.swing.GroupLayout(ListarElementosPa);
        ListarElementosPa.setLayout(ListarElementosPaLayout);
        ListarElementosPaLayout.setHorizontalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarElementosPaLayout.createSequentialGroup()
                        .addComponent(ListarEquiposRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarTecnicosRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarJugadoresRb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                .addContainerGap())
        );
        ListarElementosPaLayout.setVerticalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarEquiposRb)
                    .addComponent(ListarTecnicosRb)
                    .addComponent(ListarJugadoresRb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Principal.addTab("Listar Elementos", ListarElementosPa);

        AgregarJugadorCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(AgregarJugadorLi);

        jLabel14.setText("Escriba el nombre del jugador");

        jButton1.setText("Agregar jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ActualizarListaAgregarEquipoBt.setText("Actualizar lista");
        ActualizarListaAgregarEquipoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarListaAgregarEquipoBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarJugadoresAEquipoPaLayout = new javax.swing.GroupLayout(AgregarJugadoresAEquipoPa);
        AgregarJugadoresAEquipoPa.setLayout(AgregarJugadoresAEquipoPaLayout);
        AgregarJugadoresAEquipoPaLayout.setHorizontalGroup(
            AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarJugadorCb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgregarJugadorNombreLi, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)))
                    .addComponent(ActualizarListaAgregarEquipoBt))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        AgregarJugadoresAEquipoPaLayout.setVerticalGroup(
            AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarJugadorCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActualizarListaAgregarEquipoBt)
                .addGap(25, 25, 25)
                .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                        .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgregarJugadorNombreLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Principal.addTab("Agregar Jugadores a un Equipo", AgregarJugadoresAEquipoPa);

        jScrollPane3.setViewportView(MostrarPlantillasArbol);

        javax.swing.GroupLayout MostrarPlantillasPaLayout = new javax.swing.GroupLayout(MostrarPlantillasPa);
        MostrarPlantillasPa.setLayout(MostrarPlantillasPaLayout);
        MostrarPlantillasPaLayout.setHorizontalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        MostrarPlantillasPaLayout.setVerticalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        Principal.addTab("Mostrar Plantillas", MostrarPlantillasPa);

        Equipo1Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText("Equipo 1");

        jLabel21.setText("Equipo 2");

        JugarPartidoBt.setText("Jugar partido");
        JugarPartidoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarPartidoBtActionPerformed(evt);
            }
        });

        Equipo2Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout OrganizarPartidosPaLayout = new javax.swing.GroupLayout(OrganizarPartidosPa);
        OrganizarPartidosPa.setLayout(OrganizarPartidosPaLayout);
        OrganizarPartidosPaLayout.setHorizontalGroup(
            OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JugarPartidoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(Equipo1Cb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(Equipo2Cb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
        );
        OrganizarPartidosPaLayout.setVerticalGroup(
            OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(Equipo2Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(Equipo1Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(JugarPartidoBt)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        Principal.addTab("Organizar Partidos", OrganizarPartidosPa);

        RankingTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(RankingTb);

        javax.swing.GroupLayout MostrarRankingPaLayout = new javax.swing.GroupLayout(MostrarRankingPa);
        MostrarRankingPa.setLayout(MostrarRankingPaLayout);
        MostrarRankingPaLayout.setHorizontalGroup(
            MostrarRankingPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarRankingPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        MostrarRankingPaLayout.setVerticalGroup(
            MostrarRankingPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarRankingPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Principal.addTab("Mostrar Ranking", MostrarRankingPa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarEquipoJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarEquipoJdBtMouseClicked
        // TODO add your handling code here:
        Equipos.add(new Equipo());
        int pos = Equipos.size() - 1;
        Equipos.get(pos).setNombre(NombreEquipoTf.getText());
        Equipos.get(pos).setPais(PaisEquipoTf.getText());
    }//GEN-LAST:event_AgregarEquipoJdBtMouseClicked

    private void AgregarTecnicoJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarTecnicoJdBtMouseClicked
        // TODO add your handling code here:
        Tecnicos.add(new Tecnico());
        int pos = Tecnicos.size() - 1;
        Tecnicos.get(pos).setNombre(NombreTecnicoTf.getText());
        Tecnicos.get(pos).setEdad(Integer.parseInt(EdadTecnicoTf.getText()));
        Tecnicos.get(pos).setPais(PaisTecnicoTf.getText());
        Tecnicos.get(pos).setSalario(Float.parseFloat(SalarioTecnicoTf.getText()));
        Tecnicos.get(pos).setTiempoDeTrabajo(Float.parseFloat(TiempoDeTrabajoTecnicoTf.getText()));
        Tecnicos.get(pos).setCalidad(Integer.parseInt(CalidadTecnicoTf.getText()));
        Tecnicos.get(pos).setTipoDeJuego(TipoDeJuegoTecnicoTf.getText());
        JOptionPane.showMessageDialog(null, "Se ha agregado un técnico correctamente.");
    }//GEN-LAST:event_AgregarTecnicoJdBtMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Jugadores.add(new Jugador());
        int pos = Jugadores.size() - 1;
        Jugadores.get(pos).setNombre(NombreJugadorTf.getText());
        Jugadores.get(pos).setEdad(Integer.parseInt(EdadJugadorTf.getText()));
        Jugadores.get(pos).setPais(PaisJugadorTf.getText());
        Jugadores.get(pos).setSalario(Float.parseFloat(SalarioJugadorTf.getText()));
        if (IzquierdoRb.isSelected()) {
            Jugadores.get(pos).setPiePreferido("I");
        } else {
            Jugadores.get(pos).setPiePreferido("D");
        }
        Jugadores.get(pos).setPosicion(PosicionJugadorCb.getItemAt(PosicionJugadorCb.getSelectedIndex()));
        Jugadores.get(pos).setCalidad(Integer.parseInt(CalidadJugadorTf.getText()));
        Jugadores.get(pos).setCalidad(Integer.parseInt(CalidadJugadorTf.getText()));
        Jugadores.get(pos).setVelocidad(Float.parseFloat(VelocidadJugadorTf.getText()));
        Jugadores.get(pos).setPrecio(Float.parseFloat(PrecioJugadorTf.getText()));
    }//GEN-LAST:event_jButton2MouseClicked

    private void AgregarEquipoBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarEquipoBtMouseClicked
        // TODO add your handling code here:
        AgregarEquipo.setVisible(true);
        AgregarEquipo.pack();
    }//GEN-LAST:event_AgregarEquipoBtMouseClicked

    private void AgregarTecnicoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTecnicoBtActionPerformed
        // TODO add your handling code here:
        AgregarTecnico.setVisible(true);
        AgregarTecnico.pack();
    }//GEN-LAST:event_AgregarTecnicoBtActionPerformed

    private void AgregarJugadorBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJugadorBtActionPerformed
        // TODO add your handling code here:
        AgregarJugador.setVisible(true);
        AgregarJugador.pack();
    }//GEN-LAST:event_AgregarJugadorBtActionPerformed

    private void ListarEquiposRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarEquiposRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "País", "Calidad", "Técnico del equipo", "Puntos"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Equipos.size(); i++) {
            Object[] row = {
                Equipos.get(i).getNombre(),
                Equipos.get(i).getPais(),
                Equipos.get(i).getCalidad(),
                ((Tecnico) (Equipos.get(i).getTecnicoDelEquipo())).getNombre(),
                Equipos.get(i).getPuntos()
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarEquiposRbActionPerformed

    private void ListarTecnicosRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTecnicosRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Edad", "País", "Salario", "Tiempo de trabajo", "Calidad", "Tipo de juego"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Tecnicos.size(); i++) {
            Object[] row = {
                Tecnicos.get(i).getNombre(),
                Tecnicos.get(i).getEdad(),
                Tecnicos.get(i).getPais(),
                Tecnicos.get(i).getSalario(),
                Tecnicos.get(i).getTiempoDeTrabajo(),
                Tecnicos.get(i).getCalidad(),
                Tecnicos.get(i).getTipoDeJuego()
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarTecnicosRbActionPerformed

    private void ListarJugadoresRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarJugadoresRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Edad", "País", "Salario", "Número de camiseta",
                    "Pié preferido", "Posición", "Calidad", "Velocidad", "Precio"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Jugadores.size(); i++) {
            Object[] row = {
                Jugadores.get(i).getNombre(),
                Jugadores.get(i).getEdad(),
                Jugadores.get(i).getPais(),
                Jugadores.get(i).getSalario(),
                Jugadores.get(i).getNumeroDeCamista(),
                Jugadores.get(i).getPiePreferido(),
                Jugadores.get(i).getPosicion(),
                Jugadores.get(i).getCalidad(),
                Jugadores.get(i).getVelocidad(),
                Jugadores.get(i).getPrecio()
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarJugadoresRbActionPerformed

    private void ListarTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarTbMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            MenuClickDerecho.show(ListarTb, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ListarTbMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        Equipos.remove(ListarTb.getSelectedRow());
    }//GEN-LAST:event_EliminarActionPerformed

    private void PrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrincipalStateChanged
        // TODO add your handling code here:
        if (Principal.getSelectedIndex() == 2) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < Equipos.size(); i++) {
                modelo.addElement(Equipos.get(i).getNombre());
            }
            AgregarJugadorCb.setModel(modelo);
        }
        if (Principal.getSelectedIndex() == 3) {
            DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Equipos");
            DefaultTreeModel ModeloArbol = new DefaultTreeModel(new DefaultMutableTreeNode("Equipos"));

            for (int i = 0; i < Equipos.size(); i++) {
                DefaultMutableTreeNode NombreEquipo = new DefaultMutableTreeNode(Equipos.get(i).getNombre());
                DefaultMutableTreeNode Tecnico = new DefaultMutableTreeNode("Tecnico");
                DefaultMutableTreeNode NombreTecnico = new DefaultMutableTreeNode(Equipos.get(i).getTecnicoDelEquipo().getNombre());
                DefaultMutableTreeNode jugadoresNodo = new DefaultMutableTreeNode("Jugadores");
                for (int j = 0; j < Equipos.get(i).getJugadores().size(); j++) {
                    DefaultMutableTreeNode jugador = new DefaultMutableTreeNode(Equipos.get(i).getJugadores().get(j).getNombre());
                    jugadoresNodo.add(jugador);
                }
                Tecnico.add(NombreTecnico);
                NombreEquipo.add(jugadoresNodo);
                NombreEquipo.add(Tecnico);
                Raiz.add(NombreEquipo);
                ModeloArbol.setRoot(Raiz);

            }
            MostrarPlantillasArbol.setModel(ModeloArbol);
        }
        if (Principal.getSelectedIndex() == 4) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (int i = 0; i < Equipos.size(); i++) {
                modelo.addElement(Equipos.get(i).getNombre());
                modelo2.addElement(Equipos.get(i).getNombre());
            }
            Equipo1Cb.setModel(modelo);
            Equipo2Cb.setModel(modelo2);
        }
        if (Principal.getSelectedIndex() == 5) {
            ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Puntos", "Nombre"
                    }
            ));
            DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();
            int mayorPuntaje = 0;
            for (int i = 0; i < Equipos.size(); i++) {
                if (Equipos.get(i).getPuntos() > mayorPuntaje) {
                    mayorPuntaje = Equipos.get(i).getPuntos();
                }
            }

            for (int i = mayorPuntaje; i >= 0; i--) {
                for (int j = 0; j < Equipos.size(); j++) {
                    if (Equipos.get(j).getPuntos() == i) {
                        Object[] row = {
                            Equipos.get(j).getPuntos(),
                            Equipos.get(j).getNombre()};
                        modelo.addRow(row);
                    }
                }
            }

            RankingTb.setModel(modelo);
        }

    }//GEN-LAST:event_PrincipalStateChanged

    private void ActualizarListaAgregarEquipoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarListaAgregarEquipoBtActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().size(); i++) {
            modelo.addElement(Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().get(i).getNombre());
        }
        AgregarJugadorLi.setModel(modelo);
    }//GEN-LAST:event_ActualizarListaAgregarEquipoBtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean ExisteJugador = false;
        int IndexDelJugador = 0;
        for (int i = 0; i < Jugadores.size(); i++) {
            if (Jugadores.get(i).getNombre().equalsIgnoreCase(AgregarJugadorNombreLi.getText())) {
                ExisteJugador = true;
                IndexDelJugador = i;
            }
        }
        if (ExisteJugador) {
            Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().add(Jugadores.get(IndexDelJugador));

            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().size(); i++) {
                modelo.addElement(Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().get(i).getNombre());
            }
            AgregarJugadorLi.setModel(modelo);

            Jugadores.remove(IndexDelJugador);
            JOptionPane.showMessageDialog(this, "Se ha agregado el jugador");
        } else {
            JOptionPane.showMessageDialog(null, "No existe el jugador");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JugarPartidoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarPartidoBtActionPerformed
        // TODO add your handling code here:
        Equipos.get(Equipo1Cb.getSelectedIndex()).calcuraCalidad();
        Equipos.get(Equipo2Cb.getSelectedIndex()).calcuraCalidad();
        if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                > Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo1Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo1Cb.getSelectedIndex()).getPuntos() + 3);
            JOptionPane.showMessageDialog(this, "Ha ganado el equipo 1");
        } else if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                == Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo1Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo1Cb.getSelectedIndex()).getPuntos() + 1);
            Equipos.get(Equipo2Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo2Cb.getSelectedIndex()).getPuntos() + 1);
            JOptionPane.showMessageDialog(this, "Ha habido un empate");
        }
        if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                < Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo2Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo2Cb.getSelectedIndex()).getPuntos() + 3);
            JOptionPane.showMessageDialog(this, "Ha ganado el equipo 2");
        }
    }//GEN-LAST:event_JugarPartidoBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarListaAgregarEquipoBt;
    private javax.swing.JDialog AgregarEquipo;
    private javax.swing.JButton AgregarEquipoBt;
    private javax.swing.JButton AgregarEquipoJdBt;
    private javax.swing.JDialog AgregarJugador;
    private javax.swing.JButton AgregarJugadorBt;
    private javax.swing.JComboBox<String> AgregarJugadorCb;
    private javax.swing.JList<String> AgregarJugadorLi;
    private javax.swing.JTextField AgregarJugadorNombreLi;
    private javax.swing.JPanel AgregarJugadoresAEquipoPa;
    private javax.swing.JDialog AgregarTecnico;
    private javax.swing.JButton AgregarTecnicoBt;
    private javax.swing.JButton AgregarTecnicoJdBt;
    private javax.swing.JTextField CalidadJugadorTf;
    private javax.swing.JTextField CalidadTecnicoTf;
    private javax.swing.JPanel CreacionDeElementosPa;
    private javax.swing.JRadioButton DerechoRb;
    private javax.swing.JTextField EdadJugadorTf;
    private javax.swing.JTextField EdadTecnicoTf;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JComboBox<String> Equipo1Cb;
    private javax.swing.JComboBox<String> Equipo2Cb;
    private javax.swing.JRadioButton IzquierdoRb;
    private javax.swing.JButton JugarPartidoBt;
    private javax.swing.ButtonGroup ListarBg;
    private javax.swing.JPanel ListarElementosPa;
    private javax.swing.JRadioButton ListarEquiposRb;
    private javax.swing.JRadioButton ListarJugadoresRb;
    private javax.swing.JTable ListarTb;
    private javax.swing.JRadioButton ListarTecnicosRb;
    private javax.swing.JPopupMenu MenuClickDerecho;
    private javax.swing.JTree MostrarPlantillasArbol;
    private javax.swing.JPanel MostrarPlantillasPa;
    private javax.swing.JPanel MostrarRankingPa;
    private javax.swing.JTextField NombreEquipoTf;
    private javax.swing.JTextField NombreJugadorTf;
    private javax.swing.JTextField NombreTecnicoTf;
    private javax.swing.JPanel OrganizarPartidosPa;
    private javax.swing.JTextField PaisEquipoTf;
    private javax.swing.JTextField PaisJugadorTf;
    private javax.swing.JTextField PaisTecnicoTf;
    private javax.swing.ButtonGroup PiernaPreferidaBg;
    private javax.swing.JComboBox<String> PosicionJugadorCb;
    private javax.swing.JTextField PrecioJugadorTf;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JTable RankingTb;
    private javax.swing.JTextField SalarioJugadorTf;
    private javax.swing.JTextField SalarioTecnicoTf;
    private javax.swing.JTextField TiempoDeTrabajoTecnicoTf;
    private javax.swing.JTextField TipoDeJuegoTecnicoTf;
    private javax.swing.JTextField VelocidadJugadorTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Restaurante> Restaurantes = new ArrayList();
    ArrayList<Cancha> Canchas = new ArrayList();
    ArrayList<Carretera> Carreteras = new ArrayList();
    ArrayList<Casa> Casas = new ArrayList();
}
