/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jorgealvarez_lab5;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author ofici
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarRestauranteJd = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        NombreRestauranteTf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AgregarRestauranteJdBt = new javax.swing.JButton();
        DireccionTf = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        NivelDeSeguridadRestauranteTf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CategoriaRestauranteCb = new javax.swing.JComboBox<>();
        CalificacionCb = new javax.swing.JComboBox<>();
        AgregarCanchaJd = new javax.swing.JDialog();
        CategoriaCanchaCb = new javax.swing.JComboBox<>();
        DireccionCanchaTf = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NivelDeSeguridadCanchaTf = new javax.swing.JTextField();
        NombreCanchaTf = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        AgregarCanchaJdBt = new javax.swing.JButton();
        EstadoCanchaTf = new javax.swing.JTextField();
        AgregarCasaJd = new javax.swing.JDialog();
        NivelDeSeguridadCasaTf = new javax.swing.JTextField();
        NombreCasaTf = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        AgregarCasaJdBt = new javax.swing.JButton();
        DireccionCasaTf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        AgregarCarreteraJd = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        AgregarCarreteraJdBt = new javax.swing.JButton();
        DistanciaCarreteraTf = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        NumeroUnicoCarreteraTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LugarInicioCb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        LugarFinalCb = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        MenuClickDerecho = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        ListarElementosBg = new javax.swing.ButtonGroup();
        ListarCategoriasBg = new javax.swing.ButtonGroup();
        LugarInicioBg = new javax.swing.ButtonGroup();
        LugarFinalBg = new javax.swing.ButtonGroup();
        Principal = new javax.swing.JTabbedPane();
        CreacionDeElementosPa = new javax.swing.JPanel();
        AgregarRestauranteBt = new javax.swing.JButton();
        AgregarCanchaBt = new javax.swing.JButton();
        AgregarCasaBt = new javax.swing.JButton();
        AgregarCarreteraBt = new javax.swing.JButton();
        ListarElementosPa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListarTb = new javax.swing.JTable();
        ListarRestaurantesRb = new javax.swing.JRadioButton();
        ListarCanchasRb = new javax.swing.JRadioButton();
        ListarCarreterasRb = new javax.swing.JRadioButton();
        MostrarPlantillasPa = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListarCategoriasTr = new javax.swing.JTree();
        ListarRestaurantesCategoriaRb = new javax.swing.JRadioButton();
        ListarCanchasCategoriasRb = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        ListarCercaniaCb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListarCercaniaJl = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        jLabel23.setText("Nombre");

        jLabel25.setText("Nivel de seguridad");

        AgregarRestauranteJdBt.setText("Agregar Restaurante");
        AgregarRestauranteJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRestauranteJdBtMouseClicked(evt);
            }
        });
        AgregarRestauranteJdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRestauranteJdBtActionPerformed(evt);
            }
        });

        jLabel27.setText("Direccion");

        jLabel22.setText("Categoría");

        jLabel24.setText("Calificación");

        CategoriaRestauranteCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chino", "Mexicano", "Italiano", "Comida rápida" }));

        CalificacionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout AgregarRestauranteJdLayout = new javax.swing.GroupLayout(AgregarRestauranteJd.getContentPane());
        AgregarRestauranteJd.getContentPane().setLayout(AgregarRestauranteJdLayout);
        AgregarRestauranteJdLayout.setHorizontalGroup(
            AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarRestauranteJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                        .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalificacionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaRestauranteCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DireccionTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(NombreRestauranteTf)
                                .addComponent(NivelDeSeguridadRestauranteTf, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarRestauranteJdLayout.setVerticalGroup(
            AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(NombreRestauranteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(DireccionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(NivelDeSeguridadRestauranteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(CategoriaRestauranteCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(CalificacionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarRestauranteJdBt)
                .addContainerGap())
        );

        CategoriaCanchaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fútbol", "Básquet", "Tennis", "Volley" }));

        jLabel28.setText("Direccion");

        jLabel26.setText("Nombre");

        jLabel29.setText("Nivel de seguridad");

        jLabel30.setText("Categoría");

        jLabel31.setText("Estado");

        AgregarCanchaJdBt.setText("Agregar Cancha");
        AgregarCanchaJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCanchaJdBtMouseClicked(evt);
            }
        });
        AgregarCanchaJdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCanchaJdBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarCanchaJdLayout = new javax.swing.GroupLayout(AgregarCanchaJd.getContentPane());
        AgregarCanchaJd.getContentPane().setLayout(AgregarCanchaJdLayout);
        AgregarCanchaJdLayout.setHorizontalGroup(
            AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCanchaJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                        .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CategoriaCanchaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DireccionCanchaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(NombreCanchaTf)
                            .addComponent(NivelDeSeguridadCanchaTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EstadoCanchaTf))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarCanchaJdLayout.setVerticalGroup(
            AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(NombreCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(DireccionCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(NivelDeSeguridadCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(CategoriaCanchaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(EstadoCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarCanchaJdBt)
                .addContainerGap())
        );

        jLabel32.setText("Nivel de seguridad");

        AgregarCasaJdBt.setText("Agregar Casa");
        AgregarCasaJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCasaJdBtMouseClicked(evt);
            }
        });

        jLabel35.setText("Direccion");

        jLabel36.setText("Nombre");

        javax.swing.GroupLayout AgregarCasaJdLayout = new javax.swing.GroupLayout(AgregarCasaJd.getContentPane());
        AgregarCasaJd.getContentPane().setLayout(AgregarCasaJdLayout);
        AgregarCasaJdLayout.setHorizontalGroup(
            AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCasaJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                        .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel32))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DireccionCasaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(NombreCasaTf)
                            .addComponent(NivelDeSeguridadCasaTf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarCasaJdLayout.setVerticalGroup(
            AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(NombreCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(DireccionCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(NivelDeSeguridadCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarCasaJdBt)
                .addContainerGap())
        );

        AgregarCarreteraJdBt.setText("Agregar Carretera");
        AgregarCarreteraJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCarreteraJdBtMouseClicked(evt);
            }
        });
        AgregarCarreteraJdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCarreteraJdBtActionPerformed(evt);
            }
        });

        jLabel38.setText("Distancia");

        jLabel39.setText("Número único");

        jLabel1.setText("Lugar de inicio");

        jLabel2.setText("Lugar de final");

        LugarInicioBg.add(jRadioButton1);
        jRadioButton1.setText("Restaurante");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        LugarInicioBg.add(jRadioButton2);
        jRadioButton2.setText("Cancha");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        LugarInicioBg.add(jRadioButton3);
        jRadioButton3.setText("Casa");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        LugarFinalBg.add(jRadioButton4);
        jRadioButton4.setText("Restaurante");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        LugarFinalBg.add(jRadioButton5);
        jRadioButton5.setText("Cancha");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        LugarFinalBg.add(jRadioButton6);
        jRadioButton6.setText("Casa");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarCarreteraJdLayout = new javax.swing.GroupLayout(AgregarCarreteraJd.getContentPane());
        AgregarCarreteraJd.getContentPane().setLayout(AgregarCarreteraJdLayout);
        AgregarCarreteraJdLayout.setHorizontalGroup(
            AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCarreteraJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                        .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel2)
                            .addComponent(jLabel33)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61)
                        .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LugarInicioCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LugarFinalCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DistanciaCarreteraTf)
                            .addComponent(NumeroUnicoCarreteraTf)
                            .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton3))
                                    .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton6)))
                                .addGap(0, 87, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        AgregarCarreteraJdLayout.setVerticalGroup(
            AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(NumeroUnicoCarreteraTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(DistanciaCarreteraTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LugarInicioCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addGap(23, 23, 23)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LugarFinalCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(AgregarCarreteraJdBt)
                .addContainerGap())
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrincipalStateChanged(evt);
            }
        });

        AgregarRestauranteBt.setText("Agregar Restaurante");
        AgregarRestauranteBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRestauranteBtMouseClicked(evt);
            }
        });
        AgregarRestauranteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRestauranteBtActionPerformed(evt);
            }
        });

        AgregarCanchaBt.setText("Agregar Cancha");
        AgregarCanchaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCanchaBtActionPerformed(evt);
            }
        });

        AgregarCasaBt.setText("Agregar Casa");
        AgregarCasaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCasaBtActionPerformed(evt);
            }
        });

        AgregarCarreteraBt.setText("Agregar Carretera");
        AgregarCarreteraBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCarreteraBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreacionDeElementosPaLayout = new javax.swing.GroupLayout(CreacionDeElementosPa);
        CreacionDeElementosPa.setLayout(CreacionDeElementosPaLayout);
        CreacionDeElementosPaLayout.setHorizontalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AgregarCasaBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarRestauranteBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCanchaBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCarreteraBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        CreacionDeElementosPaLayout.setVerticalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarRestauranteBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCanchaBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCasaBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCarreteraBt)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        Principal.addTab("Creación de Elementos", CreacionDeElementosPa);

        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "País", "Calidad", "Técnico del equipo", "Puntos"
            }
        ));
        ListarTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarTbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListarTb);

        ListarElementosBg.add(ListarRestaurantesRb);
        ListarRestaurantesRb.setText("Listar Restaurantes");
        ListarRestaurantesRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarRestaurantesRbActionPerformed(evt);
            }
        });

        ListarElementosBg.add(ListarCanchasRb);
        ListarCanchasRb.setText("Listar Canchas");
        ListarCanchasRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCanchasRbActionPerformed(evt);
            }
        });

        ListarElementosBg.add(ListarCarreterasRb);
        ListarCarreterasRb.setText("Listar Carreteras");
        ListarCarreterasRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCarreterasRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListarElementosPaLayout = new javax.swing.GroupLayout(ListarElementosPa);
        ListarElementosPa.setLayout(ListarElementosPaLayout);
        ListarElementosPaLayout.setHorizontalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarElementosPaLayout.createSequentialGroup()
                        .addComponent(ListarRestaurantesRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarCanchasRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarCarreterasRb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                .addContainerGap())
        );
        ListarElementosPaLayout.setVerticalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarRestaurantesRb)
                    .addComponent(ListarCanchasRb)
                    .addComponent(ListarCarreterasRb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Principal.addTab("Listar Elementos", ListarElementosPa);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        ListarCategoriasTr.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(ListarCategoriasTr);

        ListarCategoriasBg.add(ListarRestaurantesCategoriaRb);
        ListarRestaurantesCategoriaRb.setText("Listar Restaurantes");
        ListarRestaurantesCategoriaRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarRestaurantesCategoriaRbActionPerformed(evt);
            }
        });

        ListarCategoriasBg.add(ListarCanchasCategoriasRb);
        ListarCanchasCategoriasRb.setText("Listar Canchas");
        ListarCanchasCategoriasRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCanchasCategoriasRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MostrarPlantillasPaLayout = new javax.swing.GroupLayout(MostrarPlantillasPa);
        MostrarPlantillasPa.setLayout(MostrarPlantillasPaLayout);
        MostrarPlantillasPaLayout.setHorizontalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                        .addComponent(ListarRestaurantesCategoriaRb)
                        .addGap(18, 18, 18)
                        .addComponent(ListarCanchasCategoriasRb)
                        .addGap(0, 475, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        MostrarPlantillasPaLayout.setVerticalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarRestaurantesCategoriaRb)
                    .addComponent(ListarCanchasCategoriasRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        Principal.addTab("Listar por categorías", MostrarPlantillasPa);

        ListarCercaniaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Lugar");

        jScrollPane1.setViewportView(ListarCercaniaJl);

        jButton1.setText("Actualizar lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ListarCercaniaCb, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarCercaniaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Principal.addTab("Listar por medio de cercanía", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        if (ListarRestaurantesRb.isSelected()) {
            Restaurantes.remove(ListarTb.getSelectedRow());
        }
        if (ListarCanchasRb.isSelected()) {
            Canchas.remove(ListarTb.getSelectedRow());
        }
        if (ListarCarreterasRb.isSelected()) {
            Carreteras.remove(ListarTb.getSelectedRow());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void AgregarRestauranteJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRestauranteJdBtMouseClicked
        // TODO add your handling code here:
        Restaurantes.add(new Restaurante());
        int pos = Restaurantes.size() - 1;
        Restaurantes.get(pos).setNombre(NombreRestauranteTf.getText());
        Restaurantes.get(pos).setDireccion(DireccionTf.getText());
        Restaurantes.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadRestauranteTf.getText()));
        Restaurantes.get(pos).setCategoria(CategoriaRestauranteCb.getItemAt(CategoriaRestauranteCb.getSelectedIndex()));
        Restaurantes.get(pos).setCalificacion(Integer.parseInt(CalificacionCb.getItemAt(CalificacionCb.getSelectedIndex())));
        JOptionPane.showMessageDialog(this, "Agregado");
        Lugares.add(Restaurantes.get(pos));
        AgregarRestauranteJd.setVisible(false);
    }//GEN-LAST:event_AgregarRestauranteJdBtMouseClicked

    private void AgregarCanchaJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCanchaJdBtMouseClicked
        // TODO add your handling code here:
        Canchas.add(new Cancha());
        int pos = Canchas.size() - 1;
        Canchas.get(pos).setNombre(NombreCanchaTf.getText());
        Canchas.get(pos).setDireccion(DireccionTf.getText());
        Canchas.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadCanchaTf.getText()));
        Canchas.get(pos).setCategoria(CategoriaCanchaCb.getItemAt(CategoriaCanchaCb.getSelectedIndex()));
        Canchas.get(pos).setEstado(EstadoCanchaTf.getText());
        JOptionPane.showMessageDialog(this, "Agregado");
        Lugares.add(Canchas.get(pos));
        AgregarCanchaJd.setVisible(false);
    }//GEN-LAST:event_AgregarCanchaJdBtMouseClicked

    private void AgregarCasaJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCasaJdBtMouseClicked
        // TODO add your handling code here:
        Casas.add(new Casa());
        int pos = Casas.size() - 1;
        Casas.get(pos).setNombre(NombreCasaTf.getText());
        Casas.get(pos).setDireccion(DireccionTf.getText());
        Casas.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadCasaTf.getText()));
        JOptionPane.showMessageDialog(this, "Agregado");
        Lugares.add(Casas.get(pos));
        AgregarCasaJd.setVisible(false);
    }//GEN-LAST:event_AgregarCasaJdBtMouseClicked

    private void AgregarCarreteraJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCarreteraJdBtMouseClicked

    }//GEN-LAST:event_AgregarCarreteraJdBtMouseClicked

    private void PrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrincipalStateChanged
        // TODO add your handling code here:
        if (Principal.getSelectedIndex() == 3) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < Lugares.size(); i++) {
                modelo.addElement(Lugares.get(i));
            }
            ListarCercaniaCb.setModel(modelo);
        }
    }//GEN-LAST:event_PrincipalStateChanged

    private void ListarCarreterasRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCarreterasRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Número único", "Distancia", "Lugar de inicio", "Lugar final",}
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Carreteras.size(); i++) {
            Object[] row = {
                Carreteras.get(i).getNumeroUnico(),
                Carreteras.get(i).getDistancia(),
                Carreteras.get(i).getLugarInicio().getNombre(),
                Carreteras.get(i).getLugarFinal().getNombre(),};
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarCarreterasRbActionPerformed

    private void ListarCanchasRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCanchasRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Dirección", "Nivel de seguridad",
                    "Categoría", "Estado"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Restaurantes.size(); i++) {
            Object[] row = {
                Restaurantes.get(i).getNombre(),
                Restaurantes.get(i).getDireccion(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getNivelDeSeguridad(),};
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarCanchasRbActionPerformed

    private void ListarRestaurantesRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarRestaurantesRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Dirección", "Nivel de seguridad",
                    "Categoría", "Calificación"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Restaurantes.size(); i++) {
            Object[] row = {
                Restaurantes.get(i).getNombre(),
                Restaurantes.get(i).getDireccion(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getCategoria(),
                Restaurantes.get(i).getCalificacion()
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarRestaurantesRbActionPerformed

    private void ListarTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarTbMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            MenuClickDerecho.show(ListarTb, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ListarTbMouseClicked

    private void AgregarCarreteraBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCarreteraBtActionPerformed
        // TODO add your handling code here:
        AgregarCarreteraJd.setVisible(true);
        AgregarCarreteraJd.pack();
        DefaultComboBoxModel LugarInicioCbm = new DefaultComboBoxModel();
        DefaultComboBoxModel LugarFinalCbm = new DefaultComboBoxModel();
    }//GEN-LAST:event_AgregarCarreteraBtActionPerformed

    private void AgregarCasaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCasaBtActionPerformed
        // TODO add your handling code here:
        AgregarCasaJd.setVisible(true);
        AgregarCasaJd.pack();
    }//GEN-LAST:event_AgregarCasaBtActionPerformed

    private void AgregarCanchaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCanchaBtActionPerformed
        // TODO add your handling code here:
        AgregarCanchaJd.setVisible(true);
        AgregarCanchaJd.pack();
    }//GEN-LAST:event_AgregarCanchaBtActionPerformed

    private void AgregarRestauranteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRestauranteBtActionPerformed
        // TODO add your handling code here:
        AgregarRestauranteJd.setVisible(true);
        AgregarRestauranteJd.pack();
    }//GEN-LAST:event_AgregarRestauranteBtActionPerformed

    private void AgregarRestauranteBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRestauranteBtMouseClicked
        // TODO add your handling code here:
        AgregarRestauranteJd.setVisible(true);
        AgregarRestauranteJd.pack();
    }//GEN-LAST:event_AgregarRestauranteBtMouseClicked

    private void ListarRestaurantesCategoriaRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarRestaurantesCategoriaRbActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Categorías");
        DefaultTreeModel ModeloArbol = new DefaultTreeModel(Raiz);
        DefaultMutableTreeNode Chinos = new DefaultMutableTreeNode("Chino");
        DefaultMutableTreeNode Mexicanos = new DefaultMutableTreeNode("Mexicano");
        DefaultMutableTreeNode Italianos = new DefaultMutableTreeNode("Italiano");
        DefaultMutableTreeNode ComidasRapidas = new DefaultMutableTreeNode("Comida rápida");
        for (int i = 0; i < Restaurantes.size(); i++) {
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Chino")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                Chinos.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Mexicano")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                Mexicanos.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Italiano")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                Italianos.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Comida rápida")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                ComidasRapidas.add(restaurante);
            }
        }
        Raiz.add(Chinos);
        Raiz.add(Italianos);
        Raiz.add(Mexicanos);
        Raiz.add(ComidasRapidas);
        ListarCategoriasTr.setModel(ModeloArbol);
    }//GEN-LAST:event_ListarRestaurantesCategoriaRbActionPerformed

    private void ListarCanchasCategoriasRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCanchasCategoriasRbActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Categorías");
        DefaultTreeModel ModeloArbol = new DefaultTreeModel(Raiz);
        DefaultMutableTreeNode canchasFutbol = new DefaultMutableTreeNode("Fútbol");
        DefaultMutableTreeNode canchasBasquet = new DefaultMutableTreeNode("Básquet");
        DefaultMutableTreeNode canchasTenis = new DefaultMutableTreeNode("Tenis");
        DefaultMutableTreeNode canchaseVolley = new DefaultMutableTreeNode("Volley");
        for (int i = 0; i < Restaurantes.size(); i++) {
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Fútbol")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                canchasFutbol.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Básquet")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                canchasBasquet.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Tenis")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                canchasTenis.add(restaurante);
            }
            if (Restaurantes.get(i).getCategoria().equalsIgnoreCase("Volley")) {
                DefaultMutableTreeNode restaurante
                        = new DefaultMutableTreeNode(Restaurantes.get(i).getNombre());
                canchaseVolley.add(restaurante);
            }
        }
        Raiz.add(canchasFutbol);
        Raiz.add(canchasBasquet);
        Raiz.add(canchasTenis);
        Raiz.add(canchaseVolley);
        ListarCategoriasTr.setModel(ModeloArbol);
    }//GEN-LAST:event_ListarCanchasCategoriasRbActionPerformed

    private void AgregarCarreteraJdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCarreteraJdBtActionPerformed
        // TODO add your handling code here:
        Carreteras.add(new Carretera());
        int pos = Carreteras.size() - 1;
        Carreteras.get(pos).setNumeroUnico(Integer.parseInt(NumeroUnicoCarreteraTf.getText()));
        Carreteras.get(pos).setDistancia(Float.parseFloat(DistanciaCarreteraTf.getText()));
        Carreteras.get(pos).setLugarInicio((Lugar) LugarInicioCb.getSelectedItem());
        Carreteras.get(pos).setLugarFinal((Lugar) LugarFinalCb.getSelectedItem());
        int posLugarInicio = 0;
        for (int i = 0; i < Lugares.size(); i++) {
            if (Lugares.get(i).equals(LugarInicioCb.getSelectedItem())) {
                posLugarInicio = i;
            }
        }
        Lugares.get(posLugarInicio).setCarreteraDeSalida(Carreteras.get(pos));
        int posLugarFinal = 0;
        for (int i = 0; i < Lugares.size(); i++) {
            if (Lugares.get(i).equals(LugarFinalCb.getSelectedItem())) {
                posLugarFinal = i;
            }
        }
        Lugares.get(posLugarFinal).setCarreteraDeEntrada(Carreteras.get(pos));
        JOptionPane.showMessageDialog(this, "Agregado");
        AgregarCarreteraJd.setVisible(false);
    }//GEN-LAST:event_AgregarCarreteraJdBtActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel LugarInicioCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Restaurantes.size(); i++) {
            LugarInicioCbm.addElement(Restaurantes.get(i));
        }
        LugarInicioCb.setModel(LugarInicioCbm);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel LugarInicioCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Canchas.size(); i++) {
            LugarInicioCbm.addElement(Canchas.get(i));
        }
        LugarInicioCb.setModel(LugarInicioCbm);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel LugarInicioCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Casas.size(); i++) {
            LugarInicioCbm.addElement(Casas.get(i));
        }
        LugarInicioCb.setModel(LugarInicioCbm);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel LugarFinalCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Restaurantes.size(); i++) {
            LugarFinalCbm.addElement(Restaurantes.get(i));
        }
        LugarFinalCb.setModel(LugarFinalCbm);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel LugarFinalCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Canchas.size(); i++) {
            LugarFinalCbm.addElement(Canchas.get(i));
        }
        LugarFinalCb.setModel(LugarFinalCbm);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        DefaultComboBoxModel LugarFinalCbm = new DefaultComboBoxModel();
        for (int i = 0; i < Casas.size(); i++) {
            LugarFinalCbm.addElement(Casas.get(i));
        }
        LugarFinalCb.setModel(LugarFinalCbm);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void AgregarRestauranteJdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRestauranteJdBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarRestauranteJdBtActionPerformed

    private void AgregarCanchaJdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCanchaJdBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarCanchaJdBtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel mod = new DefaultListModel();
        for (int i = 0; i < Carreteras.size(); i++) {
            if (Carreteras.get(i).getLugarInicio().
                    equals(Lugares.get(ListarCercaniaCb.getSelectedIndex()))) {
                if (Carreteras.get(i).getDistancia() < 50) {
                    mod.addElement(Carreteras.get(i).getLugarFinal());
                }
            }
        }
        for (int i = 0; i < Carreteras.size(); i++) {
            if (Carreteras.get(i).getLugarFinal().
                    equals(Lugares.get(ListarCercaniaCb.getSelectedIndex()))) {
                if (Carreteras.get(i).getDistancia() < 50) {
                    mod.addElement(Carreteras.get(i).getLugarInicio());
                }
            }
        }
        ListarCercaniaJl.setModel(mod);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCanchaBt;
    private javax.swing.JDialog AgregarCanchaJd;
    private javax.swing.JButton AgregarCanchaJdBt;
    private javax.swing.JButton AgregarCarreteraBt;
    private javax.swing.JDialog AgregarCarreteraJd;
    private javax.swing.JButton AgregarCarreteraJdBt;
    private javax.swing.JButton AgregarCasaBt;
    private javax.swing.JDialog AgregarCasaJd;
    private javax.swing.JButton AgregarCasaJdBt;
    private javax.swing.JButton AgregarRestauranteBt;
    private javax.swing.JDialog AgregarRestauranteJd;
    private javax.swing.JButton AgregarRestauranteJdBt;
    private javax.swing.JComboBox<String> CalificacionCb;
    private javax.swing.JComboBox<String> CategoriaCanchaCb;
    private javax.swing.JComboBox<String> CategoriaRestauranteCb;
    private javax.swing.JPanel CreacionDeElementosPa;
    private javax.swing.JTextField DireccionCanchaTf;
    private javax.swing.JTextField DireccionCasaTf;
    private javax.swing.JTextField DireccionTf;
    private javax.swing.JTextField DistanciaCarreteraTf;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JTextField EstadoCanchaTf;
    private javax.swing.JRadioButton ListarCanchasCategoriasRb;
    private javax.swing.JRadioButton ListarCanchasRb;
    private javax.swing.JRadioButton ListarCarreterasRb;
    private javax.swing.ButtonGroup ListarCategoriasBg;
    private javax.swing.JTree ListarCategoriasTr;
    private javax.swing.JComboBox<String> ListarCercaniaCb;
    private javax.swing.JList<String> ListarCercaniaJl;
    private javax.swing.ButtonGroup ListarElementosBg;
    private javax.swing.JPanel ListarElementosPa;
    private javax.swing.JRadioButton ListarRestaurantesCategoriaRb;
    private javax.swing.JRadioButton ListarRestaurantesRb;
    private javax.swing.JTable ListarTb;
    private javax.swing.ButtonGroup LugarFinalBg;
    private javax.swing.JComboBox<String> LugarFinalCb;
    private javax.swing.ButtonGroup LugarInicioBg;
    private javax.swing.JComboBox<String> LugarInicioCb;
    private javax.swing.JPopupMenu MenuClickDerecho;
    private javax.swing.JPanel MostrarPlantillasPa;
    private javax.swing.JTextField NivelDeSeguridadCanchaTf;
    private javax.swing.JTextField NivelDeSeguridadCasaTf;
    private javax.swing.JTextField NivelDeSeguridadRestauranteTf;
    private javax.swing.JTextField NombreCanchaTf;
    private javax.swing.JTextField NombreCasaTf;
    private javax.swing.JTextField NombreRestauranteTf;
    private javax.swing.JTextField NumeroUnicoCarreteraTf;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    ArrayList<Lugar> Lugares = new ArrayList();
    ArrayList<Restaurante> Restaurantes = new ArrayList();
    ArrayList<Cancha> Canchas = new ArrayList();
    ArrayList<Carretera> Carreteras = new ArrayList();
    ArrayList<Casa> Casas = new ArrayList();
}
