/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jorgealvarez_lab5;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ofici
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal2() {
        initComponents();
        Equipos.add(new Equipo("Barcelona", "España", new Tecnico(Float.parseFloat("12.5"), 12, "Defensivo"), 0));
        Equipos.add(new Equipo("Real Madrid", "España", new Tecnico(Float.parseFloat("12.5"), 1, "Defensivo"), 0));
        Jugadores.add(new Jugador(1, "I", "Delantero", WIDTH, TOP_ALIGNMENT, TOP_ALIGNMENT, "Neymar", WIDTH, "París", TOP_ALIGNMENT));
        Jugadores.add(new Jugador(1, "I", "Delantero", WIDTH, TOP_ALIGNMENT, TOP_ALIGNMENT, "Alejandro", WIDTH, "Francia", TOP_ALIGNMENT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarRestauranteJd = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        NombreRestauranteTf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        AgregarRestauranteJdBt = new javax.swing.JButton();
        DireccionTf = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        NivelDeSeguridadRestauranteTf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CategoriaRestauranteCb = new javax.swing.JComboBox<>();
        CalificacionCb = new javax.swing.JComboBox<>();
        AgregarCanchaJd = new javax.swing.JDialog();
        CategoriaCanchaCb = new javax.swing.JComboBox<>();
        DireccionCanchaTf = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NivelDeSeguridadCanchaTf = new javax.swing.JTextField();
        NombreCanchaTf = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        AgregarCanchaJdBt = new javax.swing.JButton();
        EstadoCanchaTf = new javax.swing.JTextField();
        AgregarCasaJd = new javax.swing.JDialog();
        NivelDeSeguridadCasaTf = new javax.swing.JTextField();
        NombreCasaTf = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        AgregarCasaJdBt = new javax.swing.JButton();
        DireccionCasaTf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        AgregarCarreteraJd = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        AgregarRestauranteJdBt1 = new javax.swing.JButton();
        DistanciaCarreteraTf = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        NumeroUnicoCarreteraTf = new javax.swing.JTextField();
        MenuClickDerecho = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Principal = new javax.swing.JTabbedPane();
        CreacionDeElementosPa = new javax.swing.JPanel();
        AgregarRestauranteBt = new javax.swing.JButton();
        AgregarCanchaBt = new javax.swing.JButton();
        AgregarCasaBt = new javax.swing.JButton();
        AgregarCarreteraBt = new javax.swing.JButton();
        ListarElementosPa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListarTb = new javax.swing.JTable();
        ListarRestaurantesRb = new javax.swing.JRadioButton();
        ListarCanchasRb = new javax.swing.JRadioButton();
        ListarCarreterasRb = new javax.swing.JRadioButton();
        AgregarJugadoresAEquipoPa = new javax.swing.JPanel();
        AgregarJugadorCb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgregarJugadorLi = new javax.swing.JList<>();
        AgregarJugadorNombreLi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ActualizarListaAgregarEquipoBt = new javax.swing.JButton();
        MostrarPlantillasPa = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MostrarPlantillasArbol = new javax.swing.JTree();
        OrganizarPartidosPa = new javax.swing.JPanel();
        Equipo1Cb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JugarPartidoBt = new javax.swing.JButton();
        Equipo2Cb = new javax.swing.JComboBox<>();
        MostrarRankingPa = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        RankingTb = new javax.swing.JTable();

        jLabel23.setText("Nombre");

        jLabel25.setText("Nivel de seguridad");

        AgregarRestauranteJdBt.setText("Agregar Restaurante");
        AgregarRestauranteJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRestauranteJdBtMouseClicked(evt);
            }
        });

        jLabel27.setText("Direccion");

        jLabel22.setText("Categoría");

        jLabel24.setText("Calificación");

        CategoriaRestauranteCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chino", "Mexicano", "Italiano", "Comida rápida" }));

        CalificacionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout AgregarRestauranteJdLayout = new javax.swing.GroupLayout(AgregarRestauranteJd.getContentPane());
        AgregarRestauranteJd.getContentPane().setLayout(AgregarRestauranteJdLayout);
        AgregarRestauranteJdLayout.setHorizontalGroup(
            AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarRestauranteJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                        .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalificacionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaRestauranteCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DireccionTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(NombreRestauranteTf)
                                .addComponent(NivelDeSeguridadRestauranteTf, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarRestauranteJdLayout.setVerticalGroup(
            AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarRestauranteJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(NombreRestauranteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(DireccionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(NivelDeSeguridadRestauranteTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(CategoriaRestauranteCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarRestauranteJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(CalificacionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarRestauranteJdBt)
                .addContainerGap())
        );

        CategoriaCanchaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fútbol", "Básquet", "Tennis", "Volley" }));

        jLabel28.setText("Direccion");

        jLabel26.setText("Nombre");

        jLabel29.setText("Nivel de seguridad");

        jLabel30.setText("Categoría");

        jLabel31.setText("Estado");

        AgregarCanchaJdBt.setText("Agregar Cancha");
        AgregarCanchaJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCanchaJdBtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AgregarCanchaJdLayout = new javax.swing.GroupLayout(AgregarCanchaJd.getContentPane());
        AgregarCanchaJd.getContentPane().setLayout(AgregarCanchaJdLayout);
        AgregarCanchaJdLayout.setHorizontalGroup(
            AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCanchaJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                        .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CategoriaCanchaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DireccionCanchaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(NombreCanchaTf)
                            .addComponent(NivelDeSeguridadCanchaTf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EstadoCanchaTf))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarCanchaJdLayout.setVerticalGroup(
            AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCanchaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(NombreCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(DireccionCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(NivelDeSeguridadCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(CategoriaCanchaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCanchaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(EstadoCanchaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarCanchaJdBt)
                .addContainerGap())
        );

        jLabel32.setText("Nivel de seguridad");

        AgregarCasaJdBt.setText("Agregar Casa");
        AgregarCasaJdBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarCasaJdBtMouseClicked(evt);
            }
        });

        jLabel35.setText("Direccion");

        jLabel36.setText("Nombre");

        javax.swing.GroupLayout AgregarCasaJdLayout = new javax.swing.GroupLayout(AgregarCasaJd.getContentPane());
        AgregarCasaJd.getContentPane().setLayout(AgregarCasaJdLayout);
        AgregarCasaJdLayout.setHorizontalGroup(
            AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCasaJdBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                        .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35)
                            .addComponent(jLabel32))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DireccionCasaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(NombreCasaTf)
                            .addComponent(NivelDeSeguridadCasaTf, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarCasaJdLayout.setVerticalGroup(
            AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCasaJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(NombreCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(DireccionCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCasaJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(NivelDeSeguridadCasaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarCasaJdBt)
                .addContainerGap())
        );

        AgregarRestauranteJdBt1.setText("Carretera");
        AgregarRestauranteJdBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRestauranteJdBt1MouseClicked(evt);
            }
        });

        jLabel38.setText("Distancia");

        jLabel39.setText("Número único");

        javax.swing.GroupLayout AgregarCarreteraJdLayout = new javax.swing.GroupLayout(AgregarCarreteraJd.getContentPane());
        AgregarCarreteraJd.getContentPane().setLayout(AgregarCarreteraJdLayout);
        AgregarCarreteraJdLayout.setHorizontalGroup(
            AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarRestauranteJdBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                        .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel33))
                        .addGap(66, 66, 66)
                        .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DistanciaCarreteraTf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(NumeroUnicoCarreteraTf))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AgregarCarreteraJdLayout.setVerticalGroup(
            AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreteraJdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(NumeroUnicoCarreteraTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarCarreteraJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(DistanciaCarreteraTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarRestauranteJdBt1)
                .addContainerGap())
        );

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        MenuClickDerecho.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrincipalStateChanged(evt);
            }
        });

        AgregarRestauranteBt.setText("Agregar Restaurante");
        AgregarRestauranteBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarRestauranteBtMouseClicked(evt);
            }
        });
        AgregarRestauranteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarRestauranteBtActionPerformed(evt);
            }
        });

        AgregarCanchaBt.setText("Agregar Cancha");
        AgregarCanchaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCanchaBtActionPerformed(evt);
            }
        });

        AgregarCasaBt.setText("Agregar Casa");
        AgregarCasaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCasaBtActionPerformed(evt);
            }
        });

        AgregarCarreteraBt.setText("Agregar Carretera");
        AgregarCarreteraBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCarreteraBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreacionDeElementosPaLayout = new javax.swing.GroupLayout(CreacionDeElementosPa);
        CreacionDeElementosPa.setLayout(CreacionDeElementosPaLayout);
        CreacionDeElementosPaLayout.setHorizontalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AgregarCasaBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarRestauranteBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCanchaBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarCarreteraBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        CreacionDeElementosPaLayout.setVerticalGroup(
            CreacionDeElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionDeElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarRestauranteBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCanchaBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCasaBt)
                .addGap(18, 18, 18)
                .addComponent(AgregarCarreteraBt)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        Principal.addTab("Creación de Elementos", CreacionDeElementosPa);

        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "País", "Calidad", "Técnico del equipo", "Puntos"
            }
        ));
        ListarTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarTbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListarTb);

        buttonGroup1.add(ListarRestaurantesRb);
        ListarRestaurantesRb.setText("Listar Restaurantes");
        ListarRestaurantesRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarRestaurantesRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(ListarCanchasRb);
        ListarCanchasRb.setText("Listar Canchas");
        ListarCanchasRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCanchasRbActionPerformed(evt);
            }
        });

        buttonGroup1.add(ListarCarreterasRb);
        ListarCarreterasRb.setText("Listar Carreteras");
        ListarCarreterasRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCarreterasRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListarElementosPaLayout = new javax.swing.GroupLayout(ListarElementosPa);
        ListarElementosPa.setLayout(ListarElementosPaLayout);
        ListarElementosPaLayout.setHorizontalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarElementosPaLayout.createSequentialGroup()
                        .addComponent(ListarRestaurantesRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarCanchasRb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListarCarreterasRb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                .addContainerGap())
        );
        ListarElementosPaLayout.setVerticalGroup(
            ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarElementosPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListarElementosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarRestaurantesRb)
                    .addComponent(ListarCanchasRb)
                    .addComponent(ListarCarreterasRb))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Principal.addTab("Listar Elementos", ListarElementosPa);

        AgregarJugadorCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(AgregarJugadorLi);

        jLabel14.setText("Escriba el nombre del jugador");

        jButton1.setText("Agregar jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ActualizarListaAgregarEquipoBt.setText("Actualizar lista");
        ActualizarListaAgregarEquipoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarListaAgregarEquipoBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarJugadoresAEquipoPaLayout = new javax.swing.GroupLayout(AgregarJugadoresAEquipoPa);
        AgregarJugadoresAEquipoPa.setLayout(AgregarJugadoresAEquipoPaLayout);
        AgregarJugadoresAEquipoPaLayout.setHorizontalGroup(
            AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarJugadorCb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgregarJugadorNombreLi, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1)))
                    .addComponent(ActualizarListaAgregarEquipoBt))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        AgregarJugadoresAEquipoPaLayout.setVerticalGroup(
            AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarJugadorCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ActualizarListaAgregarEquipoBt)
                .addGap(25, 25, 25)
                .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarJugadoresAEquipoPaLayout.createSequentialGroup()
                        .addGroup(AgregarJugadoresAEquipoPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgregarJugadorNombreLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Principal.addTab("Agregar Jugadores a un Equipo", AgregarJugadoresAEquipoPa);

        jScrollPane3.setViewportView(MostrarPlantillasArbol);

        javax.swing.GroupLayout MostrarPlantillasPaLayout = new javax.swing.GroupLayout(MostrarPlantillasPa);
        MostrarPlantillasPa.setLayout(MostrarPlantillasPaLayout);
        MostrarPlantillasPaLayout.setHorizontalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        MostrarPlantillasPaLayout.setVerticalGroup(
            MostrarPlantillasPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarPlantillasPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        Principal.addTab("Mostrar Plantillas", MostrarPlantillasPa);

        Equipo1Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText("Equipo 1");

        jLabel21.setText("Equipo 2");

        JugarPartidoBt.setText("Jugar partido");
        JugarPartidoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarPartidoBtActionPerformed(evt);
            }
        });

        Equipo2Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout OrganizarPartidosPaLayout = new javax.swing.GroupLayout(OrganizarPartidosPa);
        OrganizarPartidosPa.setLayout(OrganizarPartidosPaLayout);
        OrganizarPartidosPaLayout.setHorizontalGroup(
            OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JugarPartidoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(Equipo1Cb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(Equipo2Cb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
        );
        OrganizarPartidosPaLayout.setVerticalGroup(
            OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(OrganizarPartidosPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(Equipo2Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrganizarPartidosPaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(Equipo1Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(JugarPartidoBt)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        Principal.addTab("Organizar Partidos", OrganizarPartidosPa);

        RankingTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(RankingTb);

        javax.swing.GroupLayout MostrarRankingPaLayout = new javax.swing.GroupLayout(MostrarRankingPa);
        MostrarRankingPa.setLayout(MostrarRankingPaLayout);
        MostrarRankingPaLayout.setHorizontalGroup(
            MostrarRankingPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarRankingPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        MostrarRankingPaLayout.setVerticalGroup(
            MostrarRankingPaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarRankingPaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Principal.addTab("Mostrar Ranking", MostrarRankingPa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarRestauranteBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRestauranteBtMouseClicked
        // TODO add your handling code here:
        AgregarRestauranteJd.setVisible(true);
        AgregarRestauranteJd.pack();
    }//GEN-LAST:event_AgregarRestauranteBtMouseClicked

    private void AgregarCanchaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCanchaBtActionPerformed
        // TODO add your handling code here:
        AgregarCanchaJd.setVisible(true);
        AgregarCanchaJd.pack();
    }//GEN-LAST:event_AgregarCanchaBtActionPerformed

    private void AgregarCasaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCasaBtActionPerformed
        // TODO add your handling code here:
        AgregarCasaJd.setVisible(true);
        AgregarCasaJd.pack();
    }//GEN-LAST:event_AgregarCasaBtActionPerformed

    private void ListarRestaurantesRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarRestaurantesRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Dirección", "Nivel de seguridad",
                    "Categoría", "Calificación"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Restaurantes.size(); i++) {
            Object[] row = {
                Restaurantes.get(i).getNombre(),
                Restaurantes.get(i).getDireccion(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getCategoria(),
                Restaurantes.get(i).getCalificacion()
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarRestaurantesRbActionPerformed

    private void ListarCanchasRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCanchasRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Dirección", "Nivel de seguridad",
                    "Categoría", "Estado"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Restaurantes.size(); i++) {
            Object[] row = {
                Restaurantes.get(i).getNombre(),
                Restaurantes.get(i).getDireccion(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getNivelDeSeguridad(),
                Restaurantes.get(i).getNivelDeSeguridad(),};
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarCanchasRbActionPerformed

    private void ListarCarreterasRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCarreterasRbActionPerformed
        // TODO add your handling code here:
        ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Número único", "Distancia", "Lugar de inicio", "Lugar final"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();

        for (int i = 0; i < Carreteras.size(); i++) {
            Object[] row = {
                Carreteras.get(i).getNumeroUnico(),
                Carreteras.get(i).getDistancia(),
                Carreteras.get(i).getLugarInicio().getNombre(),
                Carreteras.get(i).getLugarFinal().getNombre(),
            };
            modelo.addRow(row);
        }
        ListarTb.setModel(modelo);
    }//GEN-LAST:event_ListarCarreterasRbActionPerformed

    private void ListarTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarTbMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            MenuClickDerecho.show(ListarTb, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ListarTbMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        Equipos.remove(ListarTb.getSelectedRow());
    }//GEN-LAST:event_EliminarActionPerformed

    private void PrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrincipalStateChanged
        // TODO add your handling code here:
        if (Principal.getSelectedIndex() == 2) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for (int i = 0; i < Equipos.size(); i++) {
                modelo.addElement(Equipos.get(i).getNombre());
            }
            AgregarJugadorCb.setModel(modelo);
        }
        if (Principal.getSelectedIndex() == 3) {
            DefaultMutableTreeNode Raiz = new DefaultMutableTreeNode("Equipos");
            DefaultTreeModel ModeloArbol = new DefaultTreeModel(new DefaultMutableTreeNode("Equipos"));

            for (int i = 0; i < Equipos.size(); i++) {
                DefaultMutableTreeNode NombreEquipo = new DefaultMutableTreeNode(Equipos.get(i).getNombre());
                DefaultMutableTreeNode Tecnico = new DefaultMutableTreeNode("Tecnico");
                DefaultMutableTreeNode NombreTecnico = new DefaultMutableTreeNode(Equipos.get(i).getTecnicoDelEquipo().getNombre());
                DefaultMutableTreeNode jugadoresNodo = new DefaultMutableTreeNode("Jugadores");
                for (int j = 0; j < Equipos.get(i).getJugadores().size(); j++) {
                    DefaultMutableTreeNode jugador = new DefaultMutableTreeNode(Equipos.get(i).getJugadores().get(j).getNombre());
                    jugadoresNodo.add(jugador);
                }
                Tecnico.add(NombreTecnico);
                NombreEquipo.add(jugadoresNodo);
                NombreEquipo.add(Tecnico);
                Raiz.add(NombreEquipo);
                ModeloArbol.setRoot(Raiz);

            }
            MostrarPlantillasArbol.setModel(ModeloArbol);
        }
        if (Principal.getSelectedIndex() == 4) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
            for (int i = 0; i < Equipos.size(); i++) {
                modelo.addElement(Equipos.get(i).getNombre());
                modelo2.addElement(Equipos.get(i).getNombre());
            }
            Equipo1Cb.setModel(modelo);
            Equipo2Cb.setModel(modelo2);
        }
        if (Principal.getSelectedIndex() == 5) {
            ListarTb.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Puntos", "Nombre"
                    }
            ));
            DefaultTableModel modelo = (DefaultTableModel) ListarTb.getModel();
            int mayorPuntaje = 0;
            for (int i = 0; i < Equipos.size(); i++) {
                if (Equipos.get(i).getPuntos() > mayorPuntaje) {
                    mayorPuntaje = Equipos.get(i).getPuntos();
                }
            }

            for (int i = mayorPuntaje; i >= 0; i--) {
                for (int j = 0; j < Equipos.size(); j++) {
                    if (Equipos.get(j).getPuntos() == i) {
                        Object[] row = {
                            Equipos.get(j).getPuntos(),
                            Equipos.get(j).getNombre()};
                        modelo.addRow(row);
                    }
                }
            }

            RankingTb.setModel(modelo);
        }

    }//GEN-LAST:event_PrincipalStateChanged

    private void ActualizarListaAgregarEquipoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarListaAgregarEquipoBtActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().size(); i++) {
            modelo.addElement(Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().get(i).getNombre());
        }
        AgregarJugadorLi.setModel(modelo);
    }//GEN-LAST:event_ActualizarListaAgregarEquipoBtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean ExisteJugador = false;
        int IndexDelJugador = 0;
        for (int i = 0; i < Jugadores.size(); i++) {
            if (Jugadores.get(i).getNombre().equalsIgnoreCase(AgregarJugadorNombreLi.getText())) {
                ExisteJugador = true;
                IndexDelJugador = i;
            }
        }
        if (ExisteJugador) {
            Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().add(Jugadores.get(IndexDelJugador));

            DefaultListModel modelo = new DefaultListModel();
            for (int i = 0; i < Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().size(); i++) {
                modelo.addElement(Equipos.get(AgregarJugadorCb.getSelectedIndex()).getJugadores().get(i).getNombre());
            }
            AgregarJugadorLi.setModel(modelo);

            Jugadores.remove(IndexDelJugador);
            JOptionPane.showMessageDialog(this, "Se ha agregado el jugador");
        } else {
            JOptionPane.showMessageDialog(null, "No existe el jugador");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JugarPartidoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarPartidoBtActionPerformed
        // TODO add your handling code here:
        Equipos.get(Equipo1Cb.getSelectedIndex()).calcuraCalidad();
        Equipos.get(Equipo2Cb.getSelectedIndex()).calcuraCalidad();
        if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                > Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo1Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo1Cb.getSelectedIndex()).getPuntos() + 3);
            JOptionPane.showMessageDialog(this, "Ha ganado el equipo 1");
        } else if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                == Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo1Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo1Cb.getSelectedIndex()).getPuntos() + 1);
            Equipos.get(Equipo2Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo2Cb.getSelectedIndex()).getPuntos() + 1);
            JOptionPane.showMessageDialog(this, "Ha habido un empate");
        }
        if (Equipos.get(Equipo1Cb.getSelectedIndex()).getCalidad()
                < Equipos.get(Equipo2Cb.getSelectedIndex()).getCalidad()) {
            Equipos.get(Equipo2Cb.getSelectedIndex()).setPuntos(
                    Equipos.get(Equipo2Cb.getSelectedIndex()).getPuntos() + 3);
            JOptionPane.showMessageDialog(this, "Ha ganado el equipo 2");
        }
    }//GEN-LAST:event_JugarPartidoBtActionPerformed

    private void AgregarRestauranteJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRestauranteJdBtMouseClicked
        // TODO add your handling code here:
        Restaurantes.add(new Restaurante());
        int pos = Restaurantes.size() - 1;
        Restaurantes.get(pos).setNombre(NombreRestauranteTf.getText());
        Restaurantes.get(pos).setDireccion(DireccionTf.getText());
        Restaurantes.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadRestauranteTf.getText()));
        Restaurantes.get(pos).setCategoria(CategoriaRestauranteCb.getItemAt(CategoriaRestauranteCb.getSelectedIndex()));
        Restaurantes.get(pos).setCalificacion(Integer.parseInt(CalificacionCb.getItemAt(CalificacionCb.getSelectedIndex())));

    }//GEN-LAST:event_AgregarRestauranteJdBtMouseClicked

    private void AgregarCanchaJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCanchaJdBtMouseClicked
        // TODO add your handling code here:
        Canchas.add(new Cancha());
        int pos = Canchas.size() - 1;
        Canchas.get(pos).setNombre(NombreCanchaTf.getText());
        Canchas.get(pos).setDireccion(DireccionTf.getText());
        Canchas.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadCanchaTf.getText()));
        Canchas.get(pos).setCategoria(CategoriaCanchaCb.getItemAt(CategoriaCanchaCb.getSelectedIndex()));
        Canchas.get(pos).setEstado(EstadoCanchaTf.getText());

    }//GEN-LAST:event_AgregarCanchaJdBtMouseClicked

    private void AgregarCasaJdBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarCasaJdBtMouseClicked
        // TODO add your handling code here:
        Casas.add(new Casa());
        int pos = Casas.size() - 1;
        Casas.get(pos).setNombre(NombreCasaTf.getText());
        Casas.get(pos).setDireccion(DireccionTf.getText());
        Casas.get(pos).setNivelDeSeguridad(Integer.parseInt(NivelDeSeguridadCasaTf.getText()));
    }//GEN-LAST:event_AgregarCasaJdBtMouseClicked

    private void AgregarRestauranteJdBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRestauranteJdBt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarRestauranteJdBt1MouseClicked

    private void AgregarRestauranteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarRestauranteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarRestauranteBtActionPerformed

    private void AgregarCarreteraBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCarreteraBtActionPerformed
        // TODO add your handling code here:
        AgregarCarreteraJd.setVisible(true);
        AgregarCarreteraJd.pack();
    }//GEN-LAST:event_AgregarCarreteraBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarListaAgregarEquipoBt;
    private javax.swing.JButton AgregarCanchaBt;
    private javax.swing.JDialog AgregarCanchaJd;
    private javax.swing.JButton AgregarCanchaJdBt;
    private javax.swing.JButton AgregarCarreteraBt;
    private javax.swing.JDialog AgregarCarreteraJd;
    private javax.swing.JButton AgregarCasaBt;
    private javax.swing.JDialog AgregarCasaJd;
    private javax.swing.JButton AgregarCasaJdBt;
    private javax.swing.JComboBox<String> AgregarJugadorCb;
    private javax.swing.JList<String> AgregarJugadorLi;
    private javax.swing.JTextField AgregarJugadorNombreLi;
    private javax.swing.JPanel AgregarJugadoresAEquipoPa;
    private javax.swing.JButton AgregarRestauranteBt;
    private javax.swing.JDialog AgregarRestauranteJd;
    private javax.swing.JButton AgregarRestauranteJdBt;
    private javax.swing.JButton AgregarRestauranteJdBt1;
    private javax.swing.JComboBox<String> CalificacionCb;
    private javax.swing.JComboBox<String> CategoriaCanchaCb;
    private javax.swing.JComboBox<String> CategoriaRestauranteCb;
    private javax.swing.JPanel CreacionDeElementosPa;
    private javax.swing.JTextField DireccionCanchaTf;
    private javax.swing.JTextField DireccionCasaTf;
    private javax.swing.JTextField DireccionTf;
    private javax.swing.JTextField DistanciaCarreteraTf;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JComboBox<String> Equipo1Cb;
    private javax.swing.JComboBox<String> Equipo2Cb;
    private javax.swing.JTextField EstadoCanchaTf;
    private javax.swing.JButton JugarPartidoBt;
    private javax.swing.JRadioButton ListarCanchasRb;
    private javax.swing.JRadioButton ListarCarreterasRb;
    private javax.swing.JPanel ListarElementosPa;
    private javax.swing.JRadioButton ListarRestaurantesRb;
    private javax.swing.JTable ListarTb;
    private javax.swing.JPopupMenu MenuClickDerecho;
    private javax.swing.JTree MostrarPlantillasArbol;
    private javax.swing.JPanel MostrarPlantillasPa;
    private javax.swing.JPanel MostrarRankingPa;
    private javax.swing.JTextField NivelDeSeguridadCanchaTf;
    private javax.swing.JTextField NivelDeSeguridadCasaTf;
    private javax.swing.JTextField NivelDeSeguridadRestauranteTf;
    private javax.swing.JTextField NombreCanchaTf;
    private javax.swing.JTextField NombreCasaTf;
    private javax.swing.JTextField NombreRestauranteTf;
    private javax.swing.JTextField NumeroUnicoCarreteraTf;
    private javax.swing.JPanel OrganizarPartidosPa;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JTable RankingTb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
    ArrayList<Restaurante> Restaurantes = new ArrayList();
    ArrayList<Cancha> Canchas = new ArrayList();
    ArrayList<Carretera> Carreteras = new ArrayList();
    ArrayList<Casa> Casas = new ArrayList();
}
